### PR TITLE
add skin changer

### PR DESCRIPTION
**Pull request by hoyame**
possibilité de changer son personnage

-- soon changer vetements

### CODE REVIEW

**Review by Rubylium — CHANGES_REQUESTED** [review]
English only in the framework please :)

**Comment by hoyame** [comment]
fix

**Review by Rubylium — CHANGES_REQUESTED** [review]
`SetEntityAsMissionEntity(PlayerPedId(), true, true)`
There is no real need to make the player ped an Mission Entity, i doubt it change anything for the player

**Comment by hoyame** [comment]
fix

**Review by Rubylium — APPROVED** [review]
Looks good for me

**Pull request merged**
